#!/usr/bin/env bash
set -euo pipefail
#
# Pi4 smoke test for CP6a — run on the Pi over SSH.
#
# Prerequisites:
#   - hostapd running on wlan1 (SENTINEL-SECURE AP)
#   - certs/server.crt and certs/server.key deployed
#   - dnsmasq installed
#   - Python venv at ./venv or system python with aiohttp + py_webauthn
#
# Usage:
#   ssh ultron@192.168.50.1
#   cd /opt/ultron/dashboard   # or wherever the repo is deployed
#   bash tools/smoke_pi.sh
#
# Laptop-only fallback (no Pi needed):
#   1. Add to hosts file:   127.0.0.1  ultron.lan
#      - Linux/macOS: sudo sh -c 'echo "127.0.0.1 ultron.lan" >> /etc/hosts'
#      - Windows:     add "127.0.0.1 ultron.lan" to C:\Windows\System32\drivers\etc\hosts
#   2. Run:
#      ULTRON_TLS_CERT=certs/server.crt ULTRON_TLS_KEY=certs/server.key \
#        ULTRON_RP_ID=ultron.lan ULTRON_ORIGINS=https://ultron.lan \
#        ULTRON_HTTPS_PORT=443 ULTRON_REDIRECT_HTTP=0 \
#        python -c "from server.main import main; main()"
#   3. Open https://ultron.lan in a browser (after installing CA cert).

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

MGMT_IF="${ULTRON_MGMT_IF:-wlan1}"
MGMT_NET="192.168.50"

fail() { echo "FAIL: $*" >&2; exit 1; }
warn() { echo "WARN: $*" >&2; }
ok()   { echo "  OK: $*"; }

echo "══ ULTRON CP6a smoke test ══"
echo ""

# ── 1. Check hostapd (SENTINEL-SECURE AP) ───────────────────────────────────
echo "── Checking hostapd on $MGMT_IF ──"
if ! ip link show "$MGMT_IF" &>/dev/null; then
    fail "$MGMT_IF interface not found. Is the AC600 plugged in?"
fi

if ! systemctl is-active --quiet hostapd 2>/dev/null; then
    fail "hostapd is not running. Start the SENTINEL-SECURE AP first:
    sudo systemctl start hostapd"
fi
ok "hostapd is active"

# ── 2. Get management IP ────────────────────────────────────────────────────
MGMT_IP=$(ip -4 addr show "$MGMT_IF" | grep -oP "inet \K${MGMT_NET}\.\d+" | head -1)
if [[ -z "$MGMT_IP" ]]; then
    fail "$MGMT_IF has no IP on $MGMT_NET.0/24. Check hostapd/dhcpcd config."
fi
ok "Management IP: $MGMT_IP"

# ── 3. Check certs ──────────────────────────────────────────────────────────
echo ""
echo "── Checking TLS certificates ──"
CERT="${ULTRON_TLS_CERT:-certs/server.crt}"
KEY="${ULTRON_TLS_KEY:-certs/server.key}"

[[ -f "$CERT" ]] || fail "Server cert not found: $CERT"
[[ -f "$KEY"  ]] || fail "Server key not found: $KEY"
ok "Cert: $CERT"
ok "Key:  $KEY"

if [[ -f ca/ca.key ]]; then
    fail "ca/ca.key found on this machine! It must stay on the admin SSD."
fi
ok "ca.key not present (correct)"

# ── 4. Install dnsmasq snippet ──────────────────────────────────────────────
echo ""
echo "── dnsmasq ──"
DNSMASQ_CONF="/etc/dnsmasq.d/ultron.conf"
DNSMASQ_SRC="tools/dnsmasq-ultron.conf"

if [[ -f "$DNSMASQ_SRC" ]]; then
    DESIRED="address=/ultron.lan/$MGMT_IP"
    if [[ -f "$DNSMASQ_CONF" ]] && grep -qF "$DESIRED" "$DNSMASQ_CONF"; then
        ok "dnsmasq already configured for ultron.lan → $MGMT_IP"
    else
        echo "  Installing $DNSMASQ_CONF with ultron.lan → $MGMT_IP"
        echo "# Auto-generated by smoke_pi.sh" | sudo tee "$DNSMASQ_CONF" >/dev/null
        echo "$DESIRED" | sudo tee -a "$DNSMASQ_CONF" >/dev/null
        sudo systemctl restart dnsmasq
        ok "dnsmasq restarted"
    fi
else
    warn "dnsmasq source $DNSMASQ_SRC not found — skipping auto-install"
fi

# ── 5. Verify DNS ───────────────────────────────────────────────────────────
echo ""
echo "── DNS verification ──"
echo "  dig @127.0.0.1 ultron.lan:"
dig @127.0.0.1 ultron.lan +short || warn "dig failed — is dnsmasq running?"

# ── 6. Determine Python ────────────────────────────────────────────────────
if [[ -f venv/bin/python ]]; then
    PY=venv/bin/python
elif command -v python3 &>/dev/null; then
    PY=python3
else
    fail "No Python found. Create a venv or install python3."
fi
ok "Python: $PY"

# ── 7. Start server ────────────────────────────────────────────────────────
echo ""
echo "── Starting ULTRON dashboard (HTTPS on $MGMT_IP:443) ──"
echo "   Press Ctrl+C to stop."
echo ""

export ULTRON_TLS_CERT="$CERT"
export ULTRON_TLS_KEY="$KEY"
export ULTRON_HTTPS_PORT=443
export ULTRON_HTTP_PORT=8080
export ULTRON_REDIRECT_HTTP=1
export ULTRON_RP_ID=ultron.lan
export ULTRON_ORIGINS=https://ultron.lan
export ULTRON_HTTP_HOST="$MGMT_IP"

# Generate one-time enrollment token
echo "── Enrollment token ──"
TOKEN=$($PY -c "
from server.auth import _db_path, _hash
from server import auth
import secrets, sqlite3
db = sqlite3.connect(str(auth._db_path()))
auth._ensure_schema(db)
tok = secrets.token_urlsafe(32)
h = auth._hash(tok)
db.execute('INSERT OR REPLACE INTO enrollment_tokens (token_hash, used) VALUES (?, 0)', (h,))
db.commit()
db.close()
print(tok)
" 2>/dev/null) || true

if [[ -n "$TOKEN" ]]; then
    echo "  Enroll URL: https://ultron.lan/?t=$TOKEN"
    echo "  (Use this ONCE to register the owner passkey)"
else
    warn "Could not generate enrollment token — register via existing method"
fi

echo ""
exec $PY -c "from server.main import main; main()"
